//
//  PlayGameModels.swift
//  RockPaperScissGame
//
//  Created by Athapong.Kor on 6/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates
//
//  Type "usecase" for some magic!

import Foundation

struct PlayGameScene {
    enum Choices: String, CaseIterable {
        case rock = "Rock"
        case paper = "Paper"
        case scissors = "Scissors"
        
        func getChoices() -> String{
            return String(self.rawValue)
        }
        
        func randomComputerChoice() -> String {
            let choices: [Choices] = [.rock, .paper, .scissors]
            let index = Int(arc4random_uniform(UInt32(choices.count)))
            let ch = choices[index]
            return ch.rawValue
        }
    }
    
    enum GameState {
        case win, lose, draw
    }
    
    struct validationResult {
        struct Request {
            let playerResult: Int
        }

        struct Response {
//            let player: String
            let computerPlay: String
        }

        struct viewModel {
            let computerPlay: String
        }
    }
}
