//
//  PlayGameRouter.swift
//  RockPaperScissGame
//
//  Created by Athapong.Kor on 6/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol PlayGameRouterInput {
    func showResult()
}

protocol PlayGameRouterDataSource: AnyObject {
    var result: String {get set}
}

protocol PlayGameRouterDataDestination: AnyObject {
    
}

class PlayGameRouter: PlayGameRouterInput {
    
    weak var viewController: PlayGameViewController!
    weak private var dataSource: PlayGameRouterDataSource!
    weak var dataDestination: PlayGameRouterDataDestination!
    
    init(viewController: PlayGameViewController, dataSource: PlayGameRouterDataSource, dataDestination: PlayGameRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    func showResult() {
        viewController.performSegue(withIdentifier: "segueShowResult", sender: viewController)
    }
    
    // MARK: Communication
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        if let vc = segue.destination as? ResultGameViewController {
            vc.router?.dataDestination.result = dataSource.result
        }
        
    }
}
