//
//  PlayGamePresenter.swift
//  RockPaperScissGame
//
//  Created by Athapong.Kor on 6/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol PlayGamePresenterInput {
    func showCompPlay(response: PlayGameScene.validationResult.Response)
    func showResult()
}

protocol PlayGamePresenterOutput: AnyObject {
    func showCompPlay(viewModel: PlayGameScene.validationResult.viewModel)
    func showResult()
}

class PlayGamePresenter: PlayGamePresenterInput {
    
    weak var output: PlayGamePresenterOutput?
    
    // MARK: Presentation logic
    
}

extension PlayGamePresenter {
    func showCompPlay(response: PlayGameScene.validationResult.Response) {
        let viewModel = PlayGameScene.validationResult.viewModel(computerPlay: response.computerPlay)
        output?.showCompPlay(viewModel: viewModel)
    }
    
    func showResult() {
        output?.showResult()
    }
}

//extension PlayGamePresenter {
//    func resultGame(result: PlayGameScene.GameState) -> String{
//        switch result {
//        case .win:
//            return "The winner is Player1!"
//        case .lose:
//            return "The winner is Computer!"
//        case .draw:
//            return "It's a Draw!"
//        }
//    }
//}
