//
//  ResultGamePresenter.swift
//  RockPaperScissGame
//
//  Created by Athapong.Kor on 10/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ResultGamePresenterInput {
    func showResult(_ result: String)
}

protocol ResultGamePresenterOutput: class {
    func showResult(_ result: String)
}

class ResultGamePresenter: ResultGamePresenterInput {
    
    weak var output: ResultGamePresenterOutput?
    
    // MARK: Presentation logic
    func showResult(_ result: String) {
        let resultGame = "\(result)"
        output?.showResult(resultGame)
    }
}
