//
//  ResultGameInteractor.swift
//  RockPaperScissGame
//
//  Created by Athapong.Kor on 10/7/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ResultGameInteractorInput {
    func showResult()
}

protocol ResultGameInteractorOutput {
    func showResult(_ result: String)
}

protocol ResultGameDataSource {
    
}

protocol ResultGameDataDestination {
    var result: String {get set}
}

class ResultGameInteractor: ResultGameInteractorInput, ResultGameDataSource, ResultGameDataDestination {
    
    var output: ResultGameInteractorOutput?
    var result: String = ""
    
    // MARK: Business logic
    func showResult() {
        output?.showResult(result)
    }

}
